AWSTemplateFormatVersion: 2010-09-09
Description: Shared Cluster Resources
# Metadata: 

Parameters: 
  BaseVPCStackName:
    Description: Cloudformation Stack that created the VPC
    Type: String

  # TODO::Inherit
  OwnerTag:
    Description: Value for the 'Owner' tag
    Type: String
  ProjectTag:
    Description: Value for the 'Project' tag
    Type: String
  EnvironmentTag:
    Description: Value for the 'Environment' tag
    Type: String
# Mappings: 

# Conditions: 

Resources: 

  # Allow resources in the cluster to speak to each other
  ClusterSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-cluster-sg
        - Key: Owner
          Value:
            Ref: OwnerTag
        - Key: Project
          Value:
            Ref: ProjectTag
        - Key: Environment
          Value:
            Ref: EnvironmentTag
        VpcId:
          Fn::ImportValue:
            Fn::Sub: ${BaseVPCStackName}-VpcId
        GroupDescription:
          Fn::Sub: ${AWS::StackName}-cluster-sg
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Fn::ImportValue:
              Fn::Sub: ${BaseVPCStackName}-VpcCidr

Outputs:
  ClusterSGId:
    Description: Cluster Security Group ID
    Value:
      Ref: ClusterSecurityGroup
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ClusterSGId
