AWSTemplateFormatVersion: 2010-09-09
Description: Subnet
Parameters:
  IsPublic:
    Description: Whether or not to build public subnets
    Type: String
    AllowedValues: ["Yes", "No"]
    Default: "No"

  GatewayID:
    Description: Whether or not to build public subnets
    Type: String
    Default: ""

  CIDRMap:
    Description: List of cidrs to pass in
    Type: CommaDelimitedList

  VpcID:
    Description: The VPC ID
    Type: String

  # EnvCIDR:
  #   Description: The CIDR range of the parent VPC
  #   AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
  #   Type: String
  NumberOfAZs:
    Type: String
    AllowedValues:
      - "1"
      - "2"
      - "3"
    Default: "2"
    Description: How many Availability Zones do you wish to utilize?

Conditions:
  IsPublic: !Equals [!Ref IsPublic, "Yes"]
  IsPrivate: !Equals [!Ref IsPublic, "No"]
  Build2: !Not [!Equals [!Ref NumberOfAZs, "1"]]
  Build3: !Equals [!Ref NumberOfAZs, "3"]
#   Build2Public:
#     "Fn::And":
#       - Fn::Equals: [IsPublic, "Yes"]
#       - !Not [!Equals [!Ref NumberOfAZs, "1"]]
#   Build3Public:
#     "Fn::And":
#       - Fn::Equals: [IsPublic, "Yes"]
#       - !Equals [!Ref NumberOfAZs, "3"]
#   Build2Private:
#     "Fn::And":
#       - Fn::Equals: [IsPublic, "No"]
#       - !Not [!Equals [!Ref NumberOfAZs, "1"]]
#   Build3Private:
#     "Fn::And":
#       - Fn::Equals: [IsPublic, "No"]
#       - !Equals [!Ref NumberOfAZs, "3"]

# The CIDR '10.20.0.0/29' is invalid. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSubnet.Range; Request ID: 6c396996-28d9-4a37-96c0-d253a84fda7a)

Resources:
  # route table
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcID
      Tags:
        - "Fn::If":
            - IsPublic
            - Key: network
              Value: public
            - !Ref AWS::NoValue
  # subnets
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VpcID
      AvailabilityZone: !Select [0, !GetAZs ]
      CidrBlock: !Select [0, !Ref CIDRMap]
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-subnet
        - "Fn::If":
            - IsPublic
            - Key: network
              Value: public
            - !Ref AWS::NoValue

  RouteAssoc1:
    Type: AWS::CloudFormation::Stack # required
    Properties:
      Parameters:
        SubnetID: !Ref Subnet1
        RtbID: !Ref RouteTable
      TemplateURL: https://craft-cf-bucket.s3.us-east-2.amazonaws.com/templates/vpc/table.yaml
      TimeoutInMinutes: 10 # not required

  # subnets
  Subnet2:
    Type: AWS::EC2::Subnet
    Condition: Build2
    Properties:
      VpcId:
        Ref: VpcID
      AvailabilityZone: !Select [1, !GetAZs ]
      CidrBlock: !Select [1, !Ref CIDRMap]
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-subnet
        - "Fn::If":
            - IsPublic
            - Key: network
              Value: public
            - !Ref AWS::NoValue

  RouteAssoc2:
    Type: AWS::CloudFormation::Stack # required
    Condition: Build2
    Properties:
      Parameters:
        SubnetID: !Ref Subnet2
        RtbID: !Ref RouteTable
      TemplateURL: https://craft-cf-bucket.s3.us-east-2.amazonaws.com/templates/vpc/table.yaml
      TimeoutInMinutes: 10 # not required

  # subnets
  Subnet3:
    Type: AWS::EC2::Subnet
    Condition: Build3
    Properties:
      VpcId:
        Ref: VpcID
      AvailabilityZone: !Select [2, !GetAZs ]
      CidrBlock: !Select [2, !Ref CIDRMap]
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-subnet
        - "Fn::If":
            - IsPublic
            - Key: network
              Value: public
            - !Ref AWS::NoValue

  RouteAssoc3:
    Type: AWS::CloudFormation::Stack # required
    Condition: Build3
    Properties:
      Parameters:
        SubnetID: !Ref Subnet3
        RtbID: !Ref RouteTable
      TemplateURL: https://craft-cf-bucket.s3.us-east-2.amazonaws.com/templates/vpc/table.yaml
      TimeoutInMinutes: 10 # not required
