AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation IAM role
# Metadata:

Parameters:
  RoleName:
    Description: Name for the new role
    Type: String
  OwnerTag:
    Description: Value for the 'Owner' tag
    Type: String
    Default: ""
  ProjectTag:
    Description: Value for the 'Project' tag
    Type: String
    Default: ""
  EnvironmentTag:
    Description: Value for the 'Environment' tag
    Type: String
    Default: ""
# Mappings:

# Conditions:

Resources:
  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::346096930733:user/icullinane
      Description: Permission for user icullinane to build things
      RoleName:
        Fn::Sub: ${AWS::StackName}-CF-role
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-${RoleName}-${EnvironmentTag}
        - Key: Owner
          Value:
            Ref: OwnerTag
        - Key: Project
          Value:
            Ref: ProjectTag
        - Key: Environment
          Value:
            Ref: EnvironmentTag

  AllowAllAccess:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: CFNUsers #required
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "cloudformation:*"
            Resource: "*"
      Users:
        - icullinane
      Roles:
        - Ref: CloudFormationRole

Outputs:
  CFRoleArn:
    Description: ARN of the CD role
    Value: !GetAtt CloudFormationRole.Arn
    Export:
      Name: CFRoleArn
